# Generated by Django 5.2.1 on 2025-12-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='显示给用户看的智能体名称', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text="用作下拉框 value 的标识，例如 'nurse-agent'", max_length=100, unique=True)),
                ('ollama_model', models.CharField(help_text='对应 Ollama 模型名，如 deepseek-r1:32b、gemma3:27b', max_length=100)),
                ('system_prompt', models.TextField(blank=True, help_text='该智能体的角色设定 / system prompt')),
                ('knowledge', models.TextField(blank=True, help_text='该智能体的背景知识或说明文本')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
