# Generated by Django 5.2.1 on 2026-06-16 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_agent_ollama_host_agent_ollama_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='知识图谱名称', max_length=100, unique=True)),
                ('ollama_host', models.CharField(default='127.0.0.1', help_text='Embedding 服务的 Ollama 主机', max_length=100)),
                ('ollama_port', models.PositiveIntegerField(default=11434, help_text='Embedding 服务的 Ollama 端口')),
                ('embedding_model', models.CharField(blank=True, help_text='用于向量化的 Ollama 模型名', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['-is_default', '-is_active', 'name']},
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('legacy', '旧版 — 文本知识'), ('kg', '知识图谱版 — 结构化知识检索')], default='legacy', help_text='智能体类型：legacy=文本知识，kg=知识图谱检索', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_default',
            field=models.BooleanField(default=False, help_text='是否默认智能体（网页端和 App 端优先选中）'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='knowledge',
            field=models.TextField(blank=True, help_text='该智能体的背景知识或说明文本（旧版使用）'),
        ),
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='知识条目标题', max_length=300)),
                ('content', models.TextField(help_text='知识内容')),
                ('source', models.CharField(blank=True, help_text='知识来源，如《神经外科护理常规》', max_length=300)),
                ('tags', models.CharField(blank=True, help_text='标签，逗号分隔', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entries', to='promotions.knowledgegraph')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='knowledge_graph',
            field=models.ForeignKey(blank=True, help_text='知识图谱版智能体绑定的知识图谱', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='promotions.knowledgegraph'),
        ),
        migrations.CreateModel(
            name='LiteratureEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='文献标题', max_length=500)),
                ('authors', models.CharField(blank=True, help_text='作者', max_length=300)),
                ('year', models.IntegerField(blank=True, help_text='发表年份', null=True)),
                ('journal', models.CharField(blank=True, help_text='期刊名称', max_length=300)),
                ('doi', models.CharField(blank=True, help_text='DOI', max_length=200)),
                ('abstract', models.TextField(help_text='摘要（用于检索匹配）')),
                ('full_text', models.TextField(blank=True, help_text='全文')),
                ('evidence_level', models.CharField(blank=True, choices=[('A', 'A级 — 多中心RCT'), ('B', 'B级 — 单中心研究'), ('C', 'C级 — 专家共识'), ('D', 'D级 — 病例报告')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literature', to='promotions.knowledgegraph')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='指南标题', max_length=200)),
                ('trigger_keywords', models.TextField(blank=True, help_text='触发关键词，每行一个。匹配到任一关键词时命中该指南')),
                ('category', models.CharField(choices=[('admission', '住院相关'), ('discharge', '出院相关'), ('medication', '用药指导'), ('rehab', '康复训练'), ('diet', '饮食管理'), ('safety', '安全管理'), ('followup', '随访复查'), ('general', '综合')], default='general', max_length=20)),
                ('media_type', models.CharField(choices=[('video', '视频'), ('image', '图片'), ('pdf', 'PDF'), ('none', '无')], default='none', max_length=10)),
                ('media_url', models.CharField(blank=True, help_text='视频/图片/PDF 链接', max_length=500)),
                ('media_timespan', models.CharField(blank=True, help_text='时间区间，如 00:09-01:39', max_length=50)),
                ('key_points', models.JSONField(default=list, help_text='要点列表 [{"label":"标题","text":"内容"},...]')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('knowledge_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_cards', to='promotions.knowledgegraph')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
