# Generated by Django 5.2.1 on 2026-06-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_knowledgegraph_alter_agent_options_agent_agent_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='knowledge_graph',
        ),
        migrations.AddField(
            model_name='agent',
            name='knowledge_graphs',
            field=models.ManyToManyField(blank=True, help_text='知识图谱版智能体绑定的知识图谱（可多选）', related_name='agents', to='promotions.knowledgegraph'),
        ),
    ]
