# Generated by Django 5.2.1 on 2026-06-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_remove_agent_knowledge_graph_agent_knowledge_graphs'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgegraph',
            name='extraction_model',
            field=models.CharField(blank=True, help_text='用于 AI 自动提取知识的 Ollama 模型名（如 qwen3:4b）', max_length=100),
        ),
        migrations.AlterField(
            model_name='knowledgegraph',
            name='ollama_host',
            field=models.CharField(default='127.0.0.1', help_text='Ollama 服务主机（embedding + 提取共用）', max_length=100),
        ),
        migrations.AlterField(
            model_name='knowledgegraph',
            name='ollama_port',
            field=models.PositiveIntegerField(default=11434, help_text='Ollama 服务端口'),
        ),
    ]
